### PR TITLE
Bugfix - Missing IE stylesheet

### LINKED ISSUE #716: main.ie.css is not minifed
Minify main.ie.css http://beta.consumerfinance.gov/static/css/main.ie.css

### LINKED ISSUE #960: Add Browser Test that catches when IE8 stylesheets are broken
It's a good a rule to add a test when we have a bug. Let's add a test to catch if a stylesheet is broken. 

It could look to see if any of the CSS rules are being applied. Using `.getCssValue` should be able to do this.

### PR DESCRIPTION
**Pull request by jimmynotjim**
Replaced old Grunt legaccsy plugin with Gulp mq-remove plugin

## Additions

- Added gulp-mq-remove plugin for IE only stylesheet
- Added gulp-rename plugin for IE only stylesheet
- Added gulp-cssmin plugin for IE only stylesheet
- Added ieStylesheet task:
  - Specifies IE 7 & 8 only vendor prefixes
  - Skips sourcemaps
  - Reduces styles to desktop size only
  - Minifies styles

## Removals

- None

## Changes

- Added `ieStyles` task to `build` task

## Testing

- Checkout branch, run ./setup.sh and check for `/dist/static/css/main.ie.css`
- If you have an IE 8 VM navigate to `http://10.0.2.2:7000`

## Review

- @KimberlyMunoz 
- @sebworks 
- @anselmbradford 

## Screenshots

screen shot 2015-09-08 at 9 00 22 am

## Notes

- Fixes #716
- Fixes #960  
- There's a bug with `:visited` links in the nav having a blue border. Will need to address in a future PR

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices 
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
Going to check this one right now, I'm also adding a task #960 to add a browser test later to catch things like this.

**Comment by jimmynotjim** [comment]
@KimberlyMunoz good call, I wasn't sure how to test for it other than requesting the stylesheet url. I will add tests for that now.

File: gulp/tasks/build.js [hunk 1]
```diff
@@ -5,6 +5,7 @@ var gulp = require( 'gulp' );
 gulp.task( 'build',
   [
     'styles',
+    'ieStyles',
```
Comment (anselmbradford) [inline gulp/tasks/build.js]: Why not `gulp styles:ie`?

**Comment by sebworks** [comment]
:+1:

**Comment by KimberlyMunoz** [comment]
LGTM. Stylesheet works. I found a few bugs in IE that are unrelated and I'll open separate tasks for them.

File: gulp/tasks/build.js (hunk 1 above)
Comment (jimmynotjim) [inline gulp/tasks/build.js]: I thought about it but I wasn't sure since we typically wouldn't want it running locally during changes triggered by `gulp watch` due to run time increases, but maybe it should? What's everyone think?

Comment (anselmbradford) [inline gulp/tasks/build.js]: Perhaps `gulp styles:modern`, `gulp styles:ie`, and `gulp styles` that runs both? Then just run `gulp styles:modern` on watch. Though if the time increase is negligible I'd get behind running it in watch to match production.

Comment (jimmynotjim) [inline gulp/tasks/build.js]: Done.
